name: nodl_to_policy CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
      # windows-latest, macos-latest
        os: [ubuntu-latest]
      fail-fast: false
    steps:
    #- uses: actions/checkout@master
    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@master
      with:
        use-ros2-testing: true
        required-ros-distributions: galactic

    - name: Run Tests
      uses: ros-tooling/action-ros-ci@master
      with:
        package-name: nodl_to_policy
        target-ros2-distro: galactic
        #colcon-mixin-name: coverage-pytest
        colcon-defaults: |
          {
            "build": {
              "mixin": ["coverage-pytest"]
            },
            "test": {
              "mixin": ["coverage-pytest"]
            }
          }
        # Pinning to a specific commit, so changes in colcon-mixin-repository don't break tests
        colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/1ddb69bedfd1f04c2f000e95452f7c24a4d6176b/index.yaml

    - uses: codecov/codecov-action@v1.2.1
      with:
        file: build/nodl_to_policy/coverage.xml
        flags: unittests,nodl_to_policy
        name: codecov-nodl_to_policy
        fail_ci_if_error: true

    - name: Upload Logs
      uses: actions/upload-artifact@v1
      with:
        name: colcon-logs
        path: ros_ws/log
      if: always()
